print("Welcome to yusuf and sons business company")
principal_amount = float(input('Enter the initial amount: '))
time_taken = float(input("Enter the time:"))
rate_applied = float(input("Enter rate of interest applied:"))
number_of_years = float(input("Enter the number of  interest years compounded annually: "))
simple_interest = principal_amount*(1 + (rate_applied * time_taken))
compound_interest = principal_amount * (1 + rate_applied /number_of_years) **(time_taken*number_of_years)
print('Simple interest is: %f' %(simple_interest))
print('Compound interest is: %f' %(compound_interest))